DIS_PRETRAINING_FAKE_SAMPLE_COUNT = 5
DIS_PRETRAINING_UPDATE_COUNT = 1

EPOCH_COUNT = 10
GEN_TRAINING_UPDATE_COUNT = 1   # Let this at 1 typically
DIS_TRAINING_FAKE_SAMPLE_COUNT = 1
DIS_TRAINING_UPDATE_COUNT = 1